@startuml

node "Client PC" {
  [Open LISA SDK] as SDK
  [Open LISA UI] as UI
}

node "Server PC" {
  [Open LISA Server] as SERVER
}

rectangle "Instruments" {
    node "Instrument 1" {
      [SCPI Interface]
    }

    node "Instrument 2" {
      [Manufacturer Custom\nInterface]
    }
}


SDK -right-> SERVER : Serial or TCP Connection
UI -right-> SERVER : Serial or TCP Connection
SERVER -right-> Instruments : USB, Serial or Ethernet Connection

@enduml
