INSTRUMENT_STATUS_AVAILABLE = "AVAILABLE"
INSTRUMENT_STATUS_UNAVAILABLE = "UNAVAILABLE"
INSTRUMENT_STATUS_NOT_REGISTERED = "NOT_REGISTERED"

COMMAND_TYPE_SET = "set"
COMMAND_TYPE_QUERY = "query"
COMMAND_TYPE_QUERY_BUFFER = "query_buffer"
COMMAND_TYPE_C_LIB = "clib"

TYPE_INT = "int"
TYPE_FLOAT = "float"