INSTRUMENT_STATUS_AVAILABLE = "AVAILABLE"
INSTRUMENT_STATUS_UNAVAILABLE = "UNAVAILABLE"
INSTRUMENT_STATUS_NOT_REGISTERED = "NOT_REGISTERED"
INSTRUMENT_STATUS_BUSY = "BUSY"

COMMAND_TYPE_SET = "set"
COMMAND_TYPE_QUERY = "query"
COMMAND_TYPE_QUERY_BUFFER = "query_buffer"
COMMAND_TYPE_C_LIB = "clib"

C_TYPE_INT = "int"
C_TYPE_FLOAT = "float"
C_TYPE_BYTES = "bytes"
C_TYPE_STRING = "string"